version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo "Package & Dependicies are getting installed"
      - npm -f install
      - echo "Packages have been installed"
      - echo "This is build phase... Zipping my lambda function"
      - zip -r mylembda-fuction.zip index.html

post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name mylembda-fuction --zip-file fileb://mylembda-fuction.zip

artifacts:
  type: zip
  paths:
    - '*'
